#!/bin/bash
set -e

echo "Starting Failback procedure using pg_rewind..."
echo "This will sync the old Primary (pitr_postgres) to match the new Primary (pitr_replica)."

# We run pg_rewind using a temporary postgres container
docker run --rm --network pitr_net \
  -v $(pwd)/../data:/var/lib/postgresql/data \
  postgres:16 pg_rewind \
  --target-pgdata=/var/lib/postgresql/data \
  --source-server='host=pitr_replica user=myuser password=mypassword dbname=postgres'

echo "Configuring old Primary to act as a Standby (Replica)..."
touch ../data/standby.signal
cat <<EOF > ../data/postgresql.auto.conf
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
primary_conninfo = 'user=myuser password=mypassword host=pitr_replica port=5432 sslmode=disable sslcompression=0 gssencmode=disable target_session_attrs=any'
EOF

echo "Starting old Primary (db) container as a Standby..."
docker compose start db

echo "Waiting for Standby to catch up..."
sleep 5

echo "================================================================"
echo "Validating Failback: Selecting data directly from Standby (pitr_postgres)..."
docker exec pitr_postgres psql -U myuser -d mydb -c "SELECT id, amount, notes FROM transactions ORDER BY created_at DESC LIMIT 3;"

echo "Inserting new data to Primary (pitr_replica) via API..."
curl -X POST http://localhost:8080/transactions \
     -H "Content-Type: application/json" \
     -d '{"amount": 750.00, "notes": "Transaksi Pasca Failback"}'

echo -e "\nWaiting 2 seconds for replication..."
sleep 2

echo "Selecting data directly from Standby (pitr_postgres) to prove replication works:"
docker exec pitr_postgres psql -U myuser -d mydb -c "SELECT id, amount, notes FROM transactions ORDER BY created_at DESC LIMIT 3;"
echo "================================================================"
echo "Failback Complete! pitr_postgres is now a replica of pitr_replica."
