# -----------------------------
# PostgreSQL configuration file
# -----------------------------

listen_addresses = '*'
port = 5432
max_connections = 100

# - Write-Ahead Log -
wal_level = replica

# - Archiving -
archive_mode = on
archive_command = 'test ! -f /var/lib/postgresql/archive/%f && cp %p /var/lib/postgresql/archive/%f'
archive_timeout = 60s

# - Replication and HA -
max_wal_senders = 10
max_replication_slots = 10
hot_standby = on
wal_log_hints = on
hba_file = '/etc/postgresql/pg_hba.conf'
